### ISSUE TITLE
Requested and source matrices have different count of elements in function 'reshape'

### ISSUE THREAD

**Issue by 27Divashree** [keshavoct98/DANCING-AI#5]
cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/matrix.cpp:1240: error: (-209:Sizes of input arguments do not match) Requested and source matrices have different count of elements in function 'reshape'.
![image](https://github.com/keshavoct98/DANCING-AI/assets/93401095/3f8ce892-059d-4d08-9ef5-716de006af19)

**Comment by keshavoct98** [comment]
Have you matches the rquirements mentioned in readme?

**Comment by 27Divashree** [comment]
> 

Yes I have matched the readme requirements.
It shows same errors at several different compatible systems.

**Comment by keshavoct98** [comment]
This project is quite old and I don't have the environment available that I used at that time. I Will try to create a colab demo with latest requirements. Will share once it is completed.

**Comment by keshavoct98** [comment]
Fixed the above mentioned issue. Also added colab demo to readme. You can check @27Divashree .
